{{- if and (not .Values.existingConfigMap.name) (not .Values.existingSecret.name) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "compass.configObjectName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "compass.labels" . | nindent 4 }}
data:
  compass.yaml: |-
    {{- .Values.config | nindent 4 }}
{{- end }}
